version: 0.0
os: linux
files:
  - source: /data
    destination: /opt/static-data
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 300
      runas: root
