version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
    overwrite: true
permissions:
  - object: /usr/share/nginx/html
    owner: root
    group: root
    mode: 755
    type:
      - directory
      - file
